[package]
name = "game_of_life_rust"
version = "0.1.0"
authors = ["Juan Antonio <JuantAldea@users.noreply.github.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
rand = "*"
rayon = "*"
termion = "*"
sdl2 = "*"
